export const FETCH_QUOTE_REQUEST='FETCH_QUOTE_REQUEST';
export const FETCH_QUOTE_SUCCESS='FETCH_QUOTE_SUCCESS';
export const FETCH_QUOTE_FAILED='FETCH_QUOTE_FAILED';


export const FETCH_TAGS_REQUEST='FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS='FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILED='FETCH_TAGS_FAILED';

export const BOOKMARKQUOTE='BOOKMARKQUOTE'
export const REMOVEQUOTE='REMOVEQUOTE'